# Python Statements - finally

[[Python Statements]] [[Python Keywords]]

---

* 用于 [[Python Exception Handling]] 中 *try* ... *except* ... *finally* 结构

    ```py
    try:
        try_block
    except:
        handler
    finally:
        final_block
    ```

* *finally* 语句下的 *final_block* 无论是否发生异常都会执行
* 常用来做一些清理工作以释放/关闭 [[Python Statements - try|try]] 子句中申请的资源

    ```python
    try:
        f = open("demofile.txt")
        f.write("Lorum Ipsum")
    except:
        print("Something went wrong when writing to the file")
    finally:
        f.close()
    ```

    * 如上例如果将 `f.close()` 写在 *try* 下语句块中, 则在写入过程出错后, 被打开的文件不会被关闭

## 优先性

* *finally* 语句具有非常高的优先性: ==[[Python Statements - try|try]] 下语句块中抛出一个异常， 或者跳出 *try* 语句时, 立即执行 *finally* 下语句块==
    * *finally* 块中的所有语句执行后, 异常被**再次触发**, 并执行 [[Python Statements - except|except]] 下异常处理语句块
    * 如果 *try* 子句中的异常没有被处理, 或者在 *except* 子句或 *else* 子句又中出现了[[Python Exception Handling#异常处理中的异常|异常]], 那么这些异常将会在 *finally* 子句执行完后**再次抛出**

* 虽然通常要加(不指定异常) [[Python Statements - except|except]] 语句, 但是**即使无 *except* 语句**, 或者出现未列出错误, 都会执行 *final_blobk*

* *finally* 甚至无法被 [[Python Statements - break|break]], [[Python Statements - continue|continue]], [[Python Statements - return|return]] 等语句跳过
    * 如在 *continue* 后

        ```py
        for i in range(2):
            try:
                if True:
                    continue
            finally:
                print('unstoppable')
        ```

        的输出为两行, 即 *finally* 下子句仍被执行了两次

    * 如在 *break* 后

        ```py
        for i in range(2):
            try:
                if True:
                    break
            finally:
                print('unstoppable')
        ```

        的输出为一行, 即 *finally* 下子句在跳出循环前仍被执行了一次
    * 如在 *return* 后

        ```py
        def f():
            try:
                return 1
            finally:
                return 'NoWay'
        ```

        调用函数 *f* 的结果为 `'NoWay'`, 即先出现的 *try* 语句下 *return* 语句不仅没能成功返回结果并跳过 *finally* 语句, 还被 *finally* 语句下的 *return* 语句抢先返回了.
        * 所以要避免*finally* 语句下的 [[Python Statements - return|return]] 语句

[//begin]: # "Autogenerated link references for markdown compatibility"
[Python Statements]: Python Statements "Python Statements"
[Python Keywords]: Python Keywords "Python Keywords"
[Python Exception Handling]: Python Exception Handling "Python Exception Handling"
[//end]: # "Autogenerated link references"